feat: FastAPI serving
sackoh/kdt-ai-aws pull request #1
Opened 2022-09-21 07:22 UTC by hyunchulshin

FastAPI serving 예제 추가

2022-09-21 07:31 UTC, sackoh requested changes
@hyunchulshin `.DS_Store` file 은 지워주실 수 있을까요 ㅠ

2022-09-21 21:48 UTC, hyunchulshin commented
fastapi만 추가한걸로 바꾸고 .DS_Store는 삭제 했습니다

2022-09-23 00:49 UTC, hyunchulshin commented
?

2022-09-23 01:44 UTC, sackoh requested changes

2022-09-23 01:44 UTC, sackoh commented on model.py
> +    def __init__(self, vectorizer_path, model_path):
@hyunchulshin 내용 지원주세요! 강의 실습하면서 채워넣을거라 여기 레포에는 빈칸으로 일부러 둔 거에요 ㅎㅎ

2022-09-23 01:44 UTC, sackoh commented on model.py
> +def get_ML_Handler():
@hyunchulshin  `get_ml_handler`로 style fix 해주쉐요

2022-09-23 01:44 UTC, sackoh commented on model.py
> +def get_DL_Handler():
@hyunchulshin  `get_dl_handler`로 style fix 해주쉐요

2022-09-23 01:44 UTC, sackoh commented on test_model_handler.py
> +    # def test_dl_model_handler(self):
@hyunchulshin  여기는 왜 주석처리 된거에요??

2022-09-26 07:10 UTC, merged